 * My Notes to self on shift work project


 * March 10, 2016
 I saved a number of papers that have to do with modeling shift work and the best one seems to be Postnova, Phillips et 
 al JBR 2012.  They use a model involving mutual inhibition between MA and VLPO and a circadian pacemaker that is entrained by light (St. Hilaire et al.).  This looks like exactly the kind of thing I need to do, but they model it in humans, not in rodents. 

 So, the first goal is to understand how (and if) two-process like models can be used for rodent polyphasic sleep and if my JMB model can be modified to work for rodents (and then to tell us something about shift work).

 I found a textbook today Principles and Practice of Sleep Medicine by Kryger, Roth and Dement and it talks about using the two-process model for rodent sleep (this text has its latest copyright of 2011 so it should be recent).  It says that Process C has yet to be incorporated in models of animal sleep.  Try to check out this book and look up references. 

 I talked with Janne:
   The experiments included 4 consecutive work shifts of 8 hours. She said the mice don't sleep at all during the work shift and are only awake 30% of the time during the light phase.  It may be possible to use a phenomenological model and assume that sleep and wake are consolidated.  She has (or can get) the following data:
        circadian
        cortisol (stress) for 4 work days
        gene expression for metabolic
        gene expression for immune
        gene expression for stress (HPA)  
  All gene expression is after the third work day.  

I read through the Postnova Phillips article and made some notes.  Some next steps: modify my model to get rid of REM/NREM dynamics (unless we have data on REM/NREM and we think it would be interesting) and think about how to do light/circadian.  I need to build the framework that we will modify to adjust for shift work. 
Should I code up the Postnova model to make sure I really understand it?  (XPP or MATLAB)

the big textbook says that light exposure can affect both C and S (Tobler et al Room light impairs sleep in the albino rat. Behav Brain Res 1994; Franken, Tobler, Borbely Varying photoperiod in the laboratory rat... Am J Physiol 1995 DeBoer and Tobler,Pflugers Arch 1997)  look these up.  

* Thursday, March 17, 2016
 I have been reading the manuscript and talking to Janne and Greg.  Some thoughts:  It sounds like no one has done the two process model on rodent data (see my comments above)

NO PROCESS C in rodent sleep models: The Neurobiology of Circadian Timing, copyright 2012, contains the following quote: "In both humans and rodents, the circadian process is not incorporated routinely in present-day modeling. There are, however, some indications that the circadian clock may influence sleep homeostatic time constants and that an effort should be made to incorporate circadian time as a variable in modeling sleep homeostasis. "


 Look up Diniz Behn papers for mouse sleep-wake behavior.  It may be relevant to the shift work stuff.  

 * Thursday, March 24, 2016
 Reading Cecilia's 2007 paper: she does not include a process C.
                               brief awakenings are explained without noise due to fixed points 
                               nudging a bit, but the sleep-active population doesn't turn off
                               during brief awakenings.

TO DO: figure out if our data show distinct differences between brief awakenings and non-brief awakenings. Same for sleep.  
        That will affect how I do the modeling. 
        - Re-read Andrew Phillips article about how two-process model and mutually inhibitory models are really the same 

thoughts: In Andrew's Mammalian Sleep Dynamics article, he shows how changing just two parameters in his model can yield results for a huge range of different mammalian sleep patterns.  I could try modifying these parameters in my model to see if I can get polyphasic sleep and then I can start modifying parameters to understand shift work.  He only fits two parameters: average daily sleep duration and average sleep episode length.   

Also, if I get my JMathBio model working for normal rodent sleep, it should be polyphasic, have the right percentages of each state (Figure 4 in shift work manuscript) and it should show nocturnal.  Phillips didn't mention anything about nocturnal or REM/NREM.  Once my model works pretty well on normal rodent data, I can see what I need to change to make it match shift work sleep.  

* Thursday, March 31, 2016
I can get "polyphasic" behaviour (more frequent transitions) out of my flip-flop code by simply changing the tau value for the rising of the homeostat.  This is similar to what Andrew shows.  However, the tau values we measured in Janne's mice shift work data are about a factor of 10 larger than what Andrew shows (3 or 4 instead of 0.3 to 0.4).  Using 0.4 gives more transitions, but it still doesn't look polyphasic to me. 

Another big issue:  Nocturnal vs. diurnal.  How to I get my model to be sleeping at the other circadian phase?  Or is their circadian curve just peaking at night rather than during the day. 

NOTES FROM TALK with Janne:  
Nocturnal:  rodents still sleep during the same phase of their circadian rythm.  It is just that their circadian rhythm is peaking during the dark while humans' peaks during the light.  The trough of rodent circadian is during the light, not during the dark. 

Rodents do the same type of sleep cycle as humans: NREM->REM with cycles lasting 10 minutes or so and several brief awakenings.  In matching model to data, Janne says to focus on timing of sleep episodes (length of sleep episodes), and it is OK to match average daily sleep duration and average sleep episode length (like Andrew Phillips does PLOS 2010), but also make sure sleep during the inactive phase is accurate.  

Figure 6 in the powerpoint showing Ti and Td differences between active phase workers and resting phase workers is a major thing I should reproduce in the model.  Both Ti and Td are higher in the resting phase workers than in the active phase workers. Can this explain the differences in sleep timing between the AW and RW groups?

The amplitude of the circadian curve changes after work for the RW group (figure that Hans made).  This is something that should be in the model:  does changing the circadian rhthym explain the longer-lasting changing in sleep timing?  

I am compiling a list of articles mentioned in Principles and Practice of Sleep Medicine with regard to the two-process model in rodents.  The first paper I'm trying to track down (Franken et al Neuroscience Letters 1991) is hard to find.  even at WSU. 



* Thursday, April 28, 2016
I met with Janne and Jonathan this morning.  We talked about the 5 state model vs. 3 state model for SWA.  We developed the 5 state model for lactate data, not SWA, so does it make sense to use it on SWA?  Does SWA really change during QW like it does during SWS?  Janne (and us) had difficulty interpreting the tau value data for the 5 state vs 3 state and active phase workers vs shift workers.  

Here is the big idea:  We are going to work on a separate manuscript to investigate this idea of the 5 state model vs. the 3-state model.  We will use the data from the shift work experiments.  Check residuals for the 5-state model and the 3-state model and vary the range used for the definition of SWA: 
1-4   2-4   3-4
1-5   2-5   3-5
1-6   2-6   3-6
1-7   2-7   3-7
1-8   2-8   3-8

optimize these individually for the active phase workers vs the resting phase workers.  
CODING:  two approaches:
1) modify my ProcessL code to allow me to define the range of frequencies to be used for finding the data to fit the model to.  Then write a script that calls it using the 5state model and the 3state model and varies the range of frequencies each time.  Do this for Active Phase workers and resting phase workers.  Output the residuals each time so I can plot them and compare between groups.  We want to say definitively that the 3state or 5state model is better, using a particular frequency range. 
2) modify my code to run Nelder-Mead to optimize not just taui and taud but also the choice of range for SWA.  This will be a separate branch of the code.  The issue is that it may choose a range that is way outside of the range that is reasonable.  

In both cases I am still only using two tau values:  one for rising (W, AW, REMS), and one for falling (SWS,QW).  

Some other thoughts:  I would like to understand what actually changes tau values and can they change with anything except genetics.  I could cook up some fake data (with noise) to see if, for instance, does shorter SWS episodes lead to faster tau values? (Set up data in a noisy exponential whose tau values I know and then remove some.  Do I see a change in tau?  The length of the SWS episode only matters in the sense of whether it is at least 5 min long or not.)  Does removing QW from the rising part of the homeostat necessarily make taui smaller?  We sometimes say these things to explain the data, but we don't really know.  

TO DO:
1) change signal to a struct that has fields .name and .freq_range.  Make .freq_range a two-element vector.  This will require changing code in PROCESSLBATCHMODE.m, DONE

2) Write code in ProcessLBatchMode.m to use signal.freq_range to find the correct columns in the .txt file to read into PhysioVars (then to construct the signal_data variable).
I started this today.  Keep going by changing lines 356 or so of ProcessLBatchmode.m to find the columns with frequencies that start or end with the requested frequencies in signal.freq_range.  


* Wednesday, June 1
I got back into coding and it looks like PROCESSLBATCHMODE is working with 1-4 Hz as the frequency range.  I should make sure that the output really matches what I had before.  It uses signal.freq_range and I cleaned up stuff related to PhysioVars.  
I'm using data from \\FS1\WisorData\Gronli\Night work, animal model\txt files\Work period\Baseline and workdays\txt files
Maybe test it with the non-GUI version of the code since I haven't updated that yet.  
I set up a little directory to test the old version and the new.  Most files look exactly the same, but 3 files look different: 4, 6 and 12.  It may be an issue of filtering.  There are some SWS episodes with large values of SWA that do not appear in the new version of the code, but do in the non-GUI version.  Check this. 


Tomorrow:  read section of textbook that I marked with post-it. READ. and I took notes.    Now read the chapter before.


* Thursday, June 2
I still can't figure out what is different between the two versions.  For file 6_AW_LD_Workday1.txt using my new version SWA goes up to 160 and in the nonGUI version it only goes up to 
1:07:  Now it works, it was some filtering I was doing in the GUI version and not the new version: exclude artifacts in EEG that were not marked as X, but are at least 3 SDs away from the mean for this animal.  I can always uncomment this code if I want.  

So at this point, PROCESSLBATCHMODE works as expected with 1-4 Hz as the frequency range.  I removed all references to PhysioVars.  

Keep checking using EEG2.  I found one bug, but I'm still not convinced EEG2 is working correctly. 
Soon start implementing it on the NOGUI version.  

NOTES FROM TALK WITH JANNE:
- Use EEG1 for all the shift work simulatons. 
- Hans believes that modeling won't tell us anything that wasn't already known (like from his paper in 2013 McCauley et. al. "Dynamic Circadian Modulation...")
  Janne doesn't think so.  She thinks there is a lot that modeling can do with regard to Active Wake and Quiet Wake.  The figure from the proposal showing SWE (slow wave energy) during quiet wake between AW and RW is pretty striking.  
- Janne will email me the location of the files I should use. 

* Friday, June 3
plan for today: 1) test PROCESSLBATCHMODE vs NOGUI using beta to make sure I am doing the frequency ranges correctly. 
                SEEMS TO WORK. I COMPUTED AVERAGES IN EXCEL AVERAGES AND   COMPARED.   
                1a) ReCheck the calculation of UA and LA.  UA doesn't seem high enough. I THINK THERE ARE LARGE TAILS SOMETIMES. 90TH PERCENTILE IS MUCH LOWER THAN MAX VALUE.  FOR NOW I WILL STICK WITH IT AS IS SINCE THIS IS WHAT FRANKEN DID.    
                2) copy NOGUI to NOGUI_BACKUP and make the same changes to NOGUI that I made to PROCESSLBATCHMODE.  DONE
                3) write the script to call NOGUI for all the different freq. ranges.  Set up a vector of strings: ['1-4' '2-5' ] etc.  That way it will 
                be easy to change which frequency ranges we use  DONE.  it is called FiveStateVsThreeStateScript.m Run this over the weekend
                3a) write another script to plot the data.  DONE and TESTED
                4) Re-read the McCauley paper from 2013
                5) Finish my profile for the SPRC website


* Monday, June 6
Notes from talk with Janne:  things to check:
1) Is Find_all_SWS_episodes.m using the custom frequency range for SWA?  YES (checked)
2)  What is L?  It seems like the model should be going down lower.  Understand why Franken computed L the way he did.  Maybe we should use a different definition of L.  OUR MODEL ISN'T GOING LOWER BECAUSE THERE IS A LOT OF WAKE EPOCHS WHEN SWA IS GETTING SMALL JUST BEFORE THE NEXT SLEEP DEPRIVATION.  I NOW PLOT UA AND LA ON THE GRAPH OF THE SWA DATA.  
3) If using the 5 state model, include 5 minute episodes of SWS and/or QW as data points, not just SWS. 

I coded up the basic two-process model in XPP today and changed the circadian curves to get something like rodent sleep in figure 18 of the Daan et al paper.  Decide if I want to keep going in XPP or switch to MATLAB.  MAtlab would make it easier to measure things like total time in each sleep stage and 


* Tuesday, June 7
Ideas:  approach this with three models: 
1) The basic homeostatic model that I have been doing (like Franken).  Add Circadian curves to this to see if it helps fit the Baseline + Workday data.  If so, run it on the whole thing: baseline+work week + recovery to see if it helps explain the long-lasting changes in sleep timing. Here is an idea of how to do that: run it by fitting it to data on the baseline+work week data.  Then just let it run after that (without fitting it to SWA data, but letting the model do what it would.  Then compare the predicted amounts of SWS and wake to what Janne actually saw in the recovery data. Before I do this, I will need a good model for the baseline data: two process with some stochastic feature (or circadian curves that are close together like Figure 18 in Daan et al) that gives the right percentages of each state at the right times (like figure 4).  Then I think the rest of this will work.  
1a) To do the stochastic version of the two process model: Come up with a stochastic function that takes in the homeostat value (as in the basic two-process model) and the light level to give a probability of each state.  The actual state will be the output of this random variable at each 10-second interval.  
2) Another idea with the basic homeostatic model (and fitting to SWA data).  Normalize the SWA data to be between 0 and 1.  Use 0 and 1 for the LA and UA respectively.  Then include circadian curves for the transitions between states.  Use NM to optimize the location and amplitude of these two curves.  The problem with this approach is that currently the model never actually reaches LA or UA so the places where the curve changes direction are determined by the sleep state at that time, not by the interaction of the homeostat with the circadian rhythm.  
3) Another idea: fit the SWA data to a basic two-process model formulation: two circadian curves and a homeostat.  Then, using data to find starting values for the homeostat and circadian curve (just after baseline day) run the two-process model for the rest of the simulation and 
All of these approaches are unlikely to explain the long-lasting changes that Janne is seeing in her data.  That is OK, it is still worth doing and worth pointing out (in my talk and in a paper)

4) To understand the long-lasting changes, I will probably need a longer-lasting variable.  Maybe something like SWE.  Think of ways to incorporate this in the modeling above.
5) With my post-doc model, modify it so it gives the baseline behavior in Janne's data (by changing C and/or stochastic).  Then do the sleep deprivation and see how the model responds.  I am guessing that it will quickly equilibriate (which is OK, we can present that too).  Then think of an additional variable that we can include that would explain the longer-lasting changes (stochastic parameters?, constant inputs to AMIN or VLPO?, changes to C?)

 All of the above approaches assume that Taui and Taud don't actually change over the course of the experiment.  If we can show that with a basic two-process model (without changing Tau values) it is impossible to predict the longer-lasting changes in sleep, then something else must be changing.  We can test which one fits the data best: changing Tau values, changing probabilities of state changes, changing C curves.   

 The paper says that 6 days were required to recover SWS.  Try to model this.  

 * Friday, June 10, 2016
 I read the McCauley Van Dongen SLEEP2013 paper and it is helpful.  They have two variables: p for performance impairment, and u for increasing the upper asymptote to which p rises during Wake, and u lowers the asymptote toward which p falls during sleep.  U simply increases during wakefulness and falls during sleep.  This is like saying the upper circadian rhythm toward which process S rises is itself increasing during wakefulness and L falls during sleep.  Why would you do that?  Also, they have the amplitude of C rising during wakefulness and exponentially falling during sleep. KEEP IN MIND THIS DID NOT FIT THE SHIFT WORK DATA WELL AT ALL.  FIGURE 2 IS THE COMPARISON TO SHIFT WORK DATA AND THE FIT IS REALLY BAD.

 IDEA:  Include SWE in the model as an output since it is the product of the # of epochs in a particular state times the average EEG power in 1-4 Hz range across all epochs of that state (measured per hour).  I can estimate this from the model if I have a prediction of sleep state from the model (with noise) and an estimate of the homeostat (process S).  
 Now, focus on how to get state changes from process S for polyphasic sleep.  Have sleep state as a separate stochastic variable that goes with S, (more likely to be in wake when S is high for instance) 
 2:36: I have a primitive model of sleep state.  I model the probability of being in a sleep state (SWS or REMS) using the sleepiness variable S-C and then shifting and scaling it so the numbers come out about right.  This pretty closely tracks the percentages of sleep states vs wake states in the baseline data.  
 Think about actually coding up a sleep state that uses these percentages to choose (stochastically) a sleep state.    
 This is almost done.  Make the plotting a little better by using fill.m to make it look like Janne's figure.  check what I have too. It may not be quite right.  

 * Monday, June 13, 2016
 It looks like wake_percentage and sleep_percentage are working correctly.  Now work on making the plot using fill.m  I have a version of this working now, but the colors aren't great. 

 * Tuesday, June 14, 2016
 I am reading papers today.  I printed the paper that Postnova cited in her shift work modeling paper in 2012.  The paper is by St. Hilaire et al. and includes Ken Wright, Czeisler, and Kronauer as co-authors.  This may be a good thing to use (or modify and use) in my modeling of Janne's shift work data since it includes a term for non-photic influences like meals and locomotor activity.  Read this paper. 

 Also read Postnova et al 2013 PLOS One paper.  They do 4 days of shift work in a model.

 One problem:  implementing the active phase protocol in my model, there is quite a bit of sleep intruding during the later part of the shift.
 major problem: implementing the resting phase work schedule gives me very little wakefulness during the scheduled work time because S-C is fairly small during during this time.  I need another way to force the system to be awake during work.  
 I added a line to force the system to be awake if working.  This helps, but the graphs still don't look great.  Keep working on this 

 * Wednesday, June 15, 2016
 I'm working on understanding the Circadian model from St. Hilaire et al.  
 The model goes all the way down to photoreceptors and is therefore light-dependent.  Janne says in our shift work experimental manuscript:  in rodents sleep/wake doesn't change much during constant darkness so it isn't a passive response to light and dark.  So we shouldn't use the same model for C. 
 However, in earlier papers by Phillips where he models sleep across many species (2010) he uses a basic model for C and calls it "well-entrained".  I think we clearly need something that is not well-entrained, like what Postnova et al used in their shift work model, but not depending on light input. 
 Will activity input be enough to set the circadian rhtym?  Ask Janne.

* Friday, June 17, 2016
Notes to self from Journal Club presentation:
Michelle said that the reason most people don't include a process C when it comes to rodents is because they keep them at 12-12 Light dark schedule.  This 12-12 schedule imposes a constant C value.  (Ask her more details about this.  I don't quite understand how it works)
Jonathan had a potentially really good idea for getting polyphasic sleep out of the two-process model: ask how far process S is from process C.  For instance, during the normal "sleep" episode the distance from the lower circadian curve could dictacte the length of the sleep episode.  This may be a good way to implement polyphasic sleep.  
Janne likes the circadian model by St Hilaire et al.  She thinks that light input is very important for mice/rats.  Talk to Ilia about C in mice.  That can help me build a model like the one from St Hilaire et al, but for rodents, not humans.  Ilia switched mice from a 12/12 Light/dark schedule to a 10/10 light/dark schedule and it really messed up sleep.  Total sleep times were not affected, but if you looked at when they slept, the sleep patterns were all messed up.  
 

* Tuesday, June 28, 2016
I'm working on coding up the circadian model of St. Hilaire et al. I was not able to get it to run in MATLAB using rk4.m or my own runge-kutta 4 step.  I am now coding it up in XPP and it initially didn't work there either. 

11:23: I was able to get a simpler version oscillating (Forger et al. 1999).  Keep going with this and try to find the typos in the more advanced versions.  equations (1) and (2) seems to work in Danny's paper.  

I was finally able to get it running in both XPP and matlab.  But when I give a nonzero light level in matlab, the computation blows up.  Now in XPP.  See what the difference is.  


FOR THE POSTER (ITALY):  In Hilaire's 2007 paper, she uses a Akaike Information Criterion to determine the goodness of fit of two different models with different numbers of parameters.  I should use this to compare the 3-state model vs. the 5-state model.  There is a penalty for adding more parameters.  See page 591 of the Hilaire paper.  Except we don't add any parameters, just states.  Still have taui and taud.    

* Monday, July 4, 2016
It looks like I finally got it running.  For a long time, it ran, but changing I did nothing.  Comparing the St Hilaire paper to the Postnova papers, it looks like Postnova left out a factor of 60 in the dn/dt equation.  I carefully worked through what the alpha0 and beta parameter values should be (considering units) and the Postnova paper was still missing a factor of 60.  Now when I change light intensity it changes the circadian curve.  

When I try to convert to hours, I'm not getting complete agreement.  Close, but not exact.  This may be a convergence issue.  Try running RK4 with smaller timesteps to make sure I have actually converged to the correct solution.  This wasn't the issue.  There was a strange little blip where the solution (when using hours, rather than seconds) would go in the wrong direction for a bit before correcting.  This would mean that the peak value would be off as compared to the version using seconds. 

I found and fixed the error:  G needs to be adjusted if alpha changes units.  the equations for dx/dt and dxc/dt are scaled by changing Omega, so everything else is those equations should be the same when you change units.  Changing the units of alpha changed the scale of B (which changed dx/dt and dxc/dt)  I divided G by 60 two times to make B have the same magnitude as when I used seconds.  This made it match up exactly with the simulation done using seconds. 

Now check the Ns parameter (so far rho=0, which turns off the non-photic input) and it that seems to be working, incorporate this circadian model into my two-process model (with the actual values of I and sleep state and think about nocturnal).  Think about which parameters I would like to optimize, etc.  

* Tuesday, July 5, 2016
I had a meeting with Janne and Jonathan this morning. Here are some outputs:
    Homestatic modeling approach for the shift work data:
      * Check the percentage of time in quiet wake (maybe not very much) around 16% or 17% one file had 32% QW for AW. 15-17% for RW so it is a significant portion of the recording.   
      * Include 5min intervals if SWS and/or QW collectively make up 90% of the 5 minutes.  Use these as data points.
        I implemented this in find_all_SWS_episodes5.m and make_freq_plot.m 
      * To determine L, the lower asymptote: try 10th percentile of SWA for L instead of the intersection with REM histogram
                                            * include SWS and QW in histogram and do the intersection with REMS histogram
                                            * include SWS and QW in histogram and do the 10th percentile
      It seems that the fit of the model is pretty dependent on the choice of UA, it is probably true of the choice of LA as well.  Should I optimize these somehow?  Either run through a set of options for UA and LA or let NM optimize? For those files where the fit of the model looks good, usually the histogram also looks good.  When the fit isn't great, the histogram doesn't look like Franken's. 23RW looks terrible with 99% for U.  It still looks bad with 90% for U. 
      I did this for U=90%,95% or 99% and L is the intersect of the two histograms or just the 10th percentile.  I made a plot of the residuals in each case (where I pooled the data from AW and RW).  It seems that the residuals are more sensitive to the choice of U than the choice of L.  For a given value of U, choosing L as 10th percentile or intersection doesn't change residuals. Using U as 99th percentile had the lowest residuals of all for both 5state model and the 3state model.  In each case the 3state model has lower residuals than the 5state model. Show this plot to Jonathan and Janne.   
      * Keep going with the idea of a variable range for SWA.  Range it up to 30Hz.  There seems to be a decline in residuals with SWA definition going up to 8 Hz.  Keep going.  Compare AW and RW on the same graph.  
      I have the code for this ready to go. Just kick it off on Friday morning.  

    Two process modeling of shift work data:
    (For the two panels I circled on my journal club powerpoint)
    * The recovery data is only for the normal resting phase.  Since the DD data show no difference between AW and RW, but the LD do, this is a process S effect, not a process C effect.  Now that I write this, I am confused.  Talk to Janne about this again.  Since removing the light, (which helps set the circadian process), neutralizes the effect between AW and RW, doesn't that imply that the difference we see in the LD case is circadian dependent? 
    * To understand the changes seen in the LD recovery panel, Janne said that it could be long-lasting changes in the MA or VLPO.  Use a mutual inhibition model for this.  
    * The new circadian model (St. Hilaire ) could be very helpful for understanding the left panel: long-lasting changes in SWS episode duration between AW and RW.
    * Implement Jonathan's idea of using the distance between S and C to determine liklihood of particular states.   
    * A BIG and IMPORTANT TO DO: I need to get actual SWS episodes into my model so I can see if they change between AW and RW.  This is the main metric I will use to compare the two (like the two figure panels)
    Also: temperature mirrors activity of SCN, so temperature activity is a good metric for circadian rhythm.   
    * Focus now on testing the 5-state model vs. the 3-state model in mouse EEG data.  I think we have only used the 5state model for lactate data.  It could be that for polysomnography, the 5-state model just doesn't work as well.  It is better for metabolic processes in sleep, but not in polysomnography.  If the 5-state model is also worse in the mouse data, we can put it to rest.  
    I found a spreadsheet with residuals for the 3-state model and 5-state model that we used in the beta paper.  Residuals are lower in the 5state model if lactate is used, but not if EEG1 or EEG2 are used.  Residuals are a bit higher in the 5state model if EEG1 is used and the same if EEG2 is used.  
    * Using shift work data, try changing the 5-min requirement for SWS episode length (try 3 and 4)  It may be that residuals go down if we use a shorter duration for SWS.  Is the 5-state model still a worse fit?  Once we have a nice fit of the model to the data, then compare shift workers and non-shift workers.  
    using RW data, and a 3 minutes requirement for SWS episode length, the 3 state model has lower residuals
    using RW data, and a 4 minute requirement for SWS episode length, changed both residuals very little.  the 3 state model still has lower residuals. 
    using AW data, and a 4 minute requirement for SWS episode length, the 3 state model has significantly lower residuals than the 5 state model
    using AW data, and a 3 minute requirement for SWS episode length, the 3 state model has lower residuals than the 5 state model
    * After comparing 5-state and 3-state, keep going on the real two process idea.  Keep trying the approach where the two C curves are very close together to see if we can get reasonable polyphasic sleep. 
    What to shoot for: Looking at the shift work manuscript, If I combine the active phases (Wake and REMS) the breakdown should be the following:
    Light:  42% W+REMS, 58% NREM
    Dark:   71% W+REMS, 29% NREM
     


    * Wednesday, July 6, 2016
    I think I found a bug: when I run the code on file 25_AW_DD_workday1.txt there are several sections where all the EEG data are 0 and the state is scored as W.  However, my model is putting data points there representing 5-min episodes of SWS.  How is this happening? This is not a bug, this is because we are using a 5 state model and these epochs were considered quiet wake (since EMG was low: 0!). 

    Don't forget to uncomment the artifact removal in both PROCESSLBATCHMODE and PROCESSLBATCHMODE_nogui that removes epocs where SWA is 0.DONE!
    
    * Thursday, July 7, 2016
    We had a journal club today on the 2016 Borbely 2-process paper. 

    * Tuesday, July 12, 2016
    Looking at the shift work data.  Two issues:  1) Right now I am using normalized RMSE since the EEG signal changes from animal to animal.  However, since I was dividing by the range of the data, that meant that recordings with higher range gave me a lower residual.  I have changed this to divide by the mean of the data, not the range. 
    2) Looking at file 8_RW_DD_workday1.txt it really seems like the delta power just after the second, third, and fourth workdays is significantly higher than after the first workday (check this in all recordings).  Does this idea lend credence to the thought that taui must change after the first work shift?  How can I quantify this to find out?  This would only work if the starting value was about the same after each work session.   
    Looking at all the files, this didn't seem to pan out, at least eye-balling it.  It did for several, but not for all. 

    I am now trying to normalize the EEG data to the average of the EEG during SWS during the first 24 hours of the recording.  I think this may get rid of the need to use NRMSE and it may make the model fit better.  I did this and it looks fine. 

    Problem files:  17_RW_DD_workday1.txt  (scattered) 

    Even using my best version of the model where the model fits the data well, and I leave out the problem files, a t-test comparing AW and RW shows no differences in either tau value between groups when I used epochs 1 to 43200.  Looking back at my emails with Janne, we separated the baseline day from the 4 work days.  Looking at the data more closely today I think that makes sense, except that the model doesn't fit the baseline data all that well.  I did seem to see faster rising during work (after the first night) than during baseline.

    I have saved all 4 spreadsheets. Check:  1) are the tau values the same between AW and RW during baseline? (i hope so) 2) are the taui and taud values different between baseline and work for both AW and QW? (we claim this in our abstract. taui for both, td for one) 3) Are the tau values different between AW and RW during the work time? Are there any differences between the groups?  

    baseline:   Ti equal
                Td equal

    I got the same results that we claim in the abstract, although with slightly higher p-values (0.005 instead of 0.001).  Still no difference between the groups during the working period.  

    * Friday, July 15
    Running the two-process model with the circ curves close together gives me a baseline average SWS episode duration that is in the right ballpark: 88.7 minutes and Janne reports about 95 minutes for the baseline in Figure 6 panel B.  I think this may be a mistake.  Make sure this is correct before I move forward. Yes, this was a typo.  Actual SWS episodes are about 90-120 seconds.  How can I get this level of detail into the two process framework?  XXC curves closer togetherXX?  C curves close together and stochastic model?  
    One issue: It seems that even with moving the C curves closer together, the sleep episodes are still way too long.  For our data, aren't the SWS episodes much shorter? 
    
    Will I need to have REMS in a model if I am doing SWS durations?   

    I requested a 1993 Achermann article that uses 2proc and does REM/NREM. 

    I tried putting the two curves close together to get polyphasic sleep and I have to get them really really close together to get anywhere near the right average SWS episode duration. I don't think this is a good approach.  For one thing, the SWS episodes are very regular since the homeostat just doesn't move that far each time.  
    ** NEXT: make a Discrete Time Markov Chain model for all three states.  If I want to get SWS episode lenghts out of the model, it seems like I will need all three states in the model, not just SWS and wake.  Using the AW and RW recordings, I computed the probability of transitioning from each state to each state (save in transition_probabilities_for_MarkovChainModel.xlsx)
     To Do Saturday: 
        1) Code up my silly little MC example to see if we are getting anywhere close to the right bout lengths in the normal case. 
        2) Look for email from Branden for a matlab version of my post-doc project (J Math Bio paper) 


* Monday, July 18
I coded up my silly little Markov Chain model and the percentages of the different states are about correct, but the bout lengths are quite a bit off. SWS and REMS episodes are too long.  I am not taking into account how long the sleep state has been in that particular state when I measured the state transition probabilities and I included the option of staying in the current state. But I didn't take into account the idea that the longer it has been in a particular state the less likely it should be to stay in that state.  Including this will help make the state episodes shorter.  I ABANDONED THIS IDEA IN FAVOR OF THE APPROACH BY KEMP AND KAMPHUISEN SLEEP 1986

2:53: I coded up the method of Kemp and Kamphuisen SLEEP 1986.  It seems to be pretty sensitive to the values of the "a" parameters, but when I used the values I estimated using the RW data, the SWS episode lengths and the REMS episode lengths are coming out pretty close to the data for the baseline case.  Think about tweaking these just slightly (or maybe using both RW and AW data to compute them) and then think about how I can interface this Markov Chain model with the 2-process stuff.  
Using RW data SWS episode length is a bit too long.  

3:40: I found a bug in the script to compute the average "a" values.  Fixing that and using both AW and RW data I am getting nice values for mean_SWS_length for the baseline, but the mean_REM_length is still a bit too short.  I get numbers around 40 when Janne reports 54.  Check to see how much the "a" values change over the course of the baseline day.  But I am averaging over the first 24 hours now, so shouldn't these come out? 

Think about how to make the two_process_model.m code interface with the Kemp_markov_chain_test_script.   

* Tuesday, July 19
One problem: the number of wake episodes is off: I am getting around 90 when there should be around 200.  I re-calculated the average number of wake episodes in the baseline day (using the data, not the model) and I get 182 on average.  I'm still way off.  How is this determined in my model?   FIXED:  I was only running my model for 12 hours, not 24.  Running it for 24 hours gives me about 180 wake episodes and mean SWS episode of about 120.  Mean SWS episode length is still a bit too high and REM episode duration is a bit too low but not by too much.   

If I go this route, using the approach of Kemp, much will rely on the values of the a_j|i.  That could be a good thing or a bad thing.  First try to estimate them for 15 minute intervals over the course of the first 24 hours to see how much they change.  If I can get the baseline looking really good (Wake episodes, SWS episode duration, REMS episode duration) then I have a solid starting point to simulate and understand the shift work.  

Small side project: remake Figure 5 using a simple two-process model.  Modify the code I have to do about 12 hours asleep and 12 hours awake.  Think about including the circadian model of St. Hilaire.  

* Wednesday, July 20
The reason the number of wake episodes goes down in Figure 6 panel B (compared to baseline) is that there is now basically one long wake episode during work as opposed to several short wake episodes during baseline.  The rats are forced to be awake for a long time and that makes the number of wake episodes lower.   

ISSUE:  Figure 5 seems to show basically consistent sleep patterns for the 4 work days after the baseline day.  Figure 6 shows that SWS episode duration changes from baseline differently for AW and RW, but is basically constant for the 4 work days (although different from baseline).  All I need in the model is a change in SWS duration for the work days as compared to the baseline day.  And this should be different for AW and RW.  Since AW and RW are working at different circadian phases, if SWS duration is dependent on C, this could explain the difference between these two groups.  So having SWS duration depend on C seems like a good idea.  Keep going with this to first match the baseline data.  

I had a good meeting with Jonathan, Janne, and Jelena.  Jonathan had the idea of a random walk to determine sleep state.  Begin as I do: choosing a uniform random variable to choose that first state.  But then do a random walk from there.  If the walker gets above the S-C curve, the state is wake.  If below, the state is S.  This isn't working out very well in practice.  It requires many runs and several times I get all SWS and no wake.  There is a lot of variability between runs even if I run 1000 random walks each time and take the average.  

* Thursday, July 21
Notes from Journal Club:  Jonathan and Janne said that the modulation of C with time is a good idea (like McCauley 2013 does) but McCauley seems to do it in the wrong direction.  C amplitude should decrease with extended wakefulness and increase during sleep.  Look up the DeBoer et al Nat Neurosci 2003 reference (Sleep states alter activity of suprachiasmatic nucleus neurons.)  ASK JW and JANNE about this since it seems to be opposite of the Nat Neurosci paper.  Nat Neurosci and McCauley seem to agree now.  

another note from our conversation:  C amplitude is compressed in the RW (as compared to the AW?)  In AW in DD it takes a few days for C to recover to its normal amplitude. 
More activity in the dark phase increases C amplitude. 

* Monday, August 1
Prioritize:
1) Figure out why the mean REM length is so far off.  This may involve computing the a_i,j values over one-hour intervals instead of over 12 or 24 hours.  I may also need additional data from Janne: number of SWS episodes, number of REMS episodes, W episode duration.  These may all be in the sleepreport.  Also, see what Jonathan considers an actual W episode: at least 20 seconds?  this would affect episode duration for REMS. 
RESULTS:
I have a spreadsheet for these data, but they don't match up with the figure.  Ask J and J about it.  
2) C curve: 
    a) Figure out if Jonathan and Janne's comments match with the Nat Neurosci paper (that McCauley seems to agree with). They seem to be opposite.  Schedule a meeting to talk about this. Or just stop in to offices.    
    b) Determine if I want to keep messing with the St. Hilaire model or use Hans' (or something different)
       My C model needs: light input, non-photic input (like work or sleep state). It looks like maybe the St. Hilaire model already includes the rise in C amplitude during wake and fall during sleep. 
       I spent a lot of time on the St. Hilaire C model since McCauley mentions their work at the end of the manuscript saying it would be a future direction.  The St. Hilaire model already includes the effect of light and activity which is what I want.  
       Perhaps the fastest approach would be to add light and/or activity to the model that McCauley uses.  Or step back to earlier versions of the model and try to find parameter values. 
       New idea for C:  stereotype the C curves for AW and RW.  Can the change in C explain differences between the two groups?  
       Figure out how to make the transition rates depend on C and/or S (or )  


* Tuesday, August 2
I met with Jonathan and Janne this morning.  We talked mostly about circadian curves.  Instead of sorting out the difference between Hans and the Nat Neurosci paper, just start from our data:  C amplitude is compresssed for RW and opposite for AW.  


* Wednesday, August 3
I realized this morning that I had a mistake in my logic:  I was thinking of the sleep drive (homeostat) as being a global variable that determines which states are more likely to be entered at certain times.  But I didn't have the sleep state affecting the homestat as it should.  After talking with Janne and thinking about it, I have decided that I think I can still use my markov state model and have the homeostat change direction based on state.  
Steps:
    1) initialize H
    2) use current value of H (and C?) to update a_ij  or I can just measure a_ij for individual rats in 1 or 2 hour intervals.  
    3) choose state and duration of episode in that state using Markov Model of Kemp
    4) update H accordingly (up or down for the duration of that state)
    repeat

I have a version of this running.  So far the transition rates a_ji are constants, but I should be able to change them based on the homeostat and Circadian curves.   Right now the mean SWS episode duration is a bit too high, mean REM length is a bit too high, number of wake episodes is a bit too low (about 175 instead of 200).  Perhaps these can all be fixed by tweaking the a_ji a bit.  
I modified ahat_W_S and ahat_R_S and now the mean SWS episode length seems to be right on.  I could compute an average over many trials to make sure, but it looks good.  Keep going with this.  
I have modified ahat_W_R and ahat_S_R and now the mean REMS episode length seems to be correct too.  The total number of wake episodes is still a bit too low, but it is closer than it was. 

TO DO:
- Think about writing a script that runs the MC model 100 times and plots the average of all the traces.  There is quite a bit of variation in trace to trace if I don't have sleep deprivation turned on. Think about just modifying two_process_model_with_markov_chain.m to do this.  it shouldn't be too hard.   
It would also be good to make sure that the averages of SWS episode length and and REMS episode length and wake episodes is averaging out correctly. This could also be coded in two_process_model_with_markov_chain.m  
DONE: I now run the MC simulation many times and compute the global averages of episode length and they are all coming out just about perfect. 

- Then think about how to modify the a_ji terms using S-C to get more of each state at particular phases (like Figure 5.  Janne put the Excel file for these data on FS1)

- Get the data for Figure 6 in an excel spreadsheet and add the values from my simulations for the baseline.  Put in comments, perhaps in another tab. 
I will use this to make a new version of Figure 6 where I overlay the data from the simulations. 
UPDATE: I emailed Janne about this. 
I have saved these data in a matlab workspace called FIG6_Experimental_Data.mat.  It is on FS1 in my shift_work model directory.  I have a script to plot the data.     

- Make a graph of percentages of each sleep state like Figure 5 so I can compare my baseline to the data.  Also, remake Figure 5 without the active Wake and Quiet Wake.  
UPDATE: I have remade Figure 5 without AW and QW and saved the two pdf's in the Shift_work_project folder on FS1.  They are called Fig_5_panelA_wake_groupedNEW.pdf and the same thing with panelB.  I still need to format these for font size and labels, etc. but that seems to work in Illustrator.
My code two-process-model-withMarkovChain.m now calls make_shaded_state_percentages_plot.m and it seems to work.  The colors could be improved a bit, but it works.    


* Friday, August 5, 2016
Remember that I can change Ti and Td in the model between the baseline day and the workdays as I stated in the abstract for ESRS.  This, combined with changes in the circadian rhythm may be enough to explain the differences between AW and RW?  

I plotted SWS bout duration vs time in AW and RW and saved the figure in BoutAnalysis_360-Epochs_with_chart.xlsx.  There is a circadian trend to SWS bout duration during the baseline and a sharp rise after working and then a gradual decline. 

I wrote a script to replot the experimental data in Figure 6 panel B.  It is called script_to_plot_experimental_data_in_Figure6.m 

When I plot S-C the curve basically looks circadian, because the homeostat does not change much during the baseline.  Looking at the data, the amount of SWS and REMS seems to be proportional to S-C.  Wake is opposite.  If I can modify the a_ij in this direction I should be able to make simulations that look a whole lot like Figure 5.   

TO DO:  1) Run the model with sleep deprivation for AW to see if I can really make a plot that looks like Figure 5 in the paper. DONE
        2) Try 1) with the RW too. 
        3) Look deeper into the Circadian curve stuff (and remember changes in tau values) to see if I can really start seeing some 
           differences between AW and RW based on differences in C.  


* Tuesday, August 9, 2016
I have the model running and it looks great in terms of making Figure 5 for AW.  But the number of wake episodes and the bout durations of SWS and REMS are not matching up with data. SWS and REMS are flat over the days.  This is all with constant tau values and a basic C curve.  I can begin changing things to see if I can change the episode duration without changing the percentages, but it would be nice to know why SWS episode duration isn't going up like in the data.  The homeostat goes way up so I expected the SWS episode duration to go way up.  Is it not lasting long enough? 

Episode durations are constant for SWS in the RW case too.  No change over the workdays.  
NOTE: IMPORTANT: Be careful where I am measuring SWS episode duration.  It is only during non-working hours.  FIXED  
What could be changing SWS episode duration in the data and not in the model?

Things to check: 1) Changing C (amplitude and/or global level)
                  2) Changing tau values between baseline and Work days?  Try our tau values instead of those from Franken. 
                  I may need to figure out if SWS episodes are getting longer at first after sleep deprivation or not.
                  UPDATE: I plotted the SWS episode duration over 1-hour segments and it is not higher just after sleep deprivation.  Why are the sleep episodes not longer after sleep deprivation? ahat_W_S is getting down to 0, CHECK THIS. It looks like after sleep dep, ahat_R_S is getting larger than normal, meaning that the wait time to transition into REMS is actually shorter, not longer.  I bet that after sleep dep, the system transitions from SWS to REMS much more frequently than SWS->Wake.  This could be why SWS episodes are not any longer after sleep dep. 
                  The problem is in how I am modeling REMS and SWS.  Both SWS and REMS are more likely when the homeostat is high, so instead of getting long SWS episodes when the homeostat is high, REMS is more likely then too, so the system transitions from SWS to REM. 
                  IDEA: make REM not depend on the homeostat

* Wednesday, August 10, 2016
But the problem with that was that when the homeostat was high, during recovery sleep I didnt get longer SWS episodes.  They would transition quickly into REMS episodes because REMS need was high too.  
This implies that the homestat that I am thinking of is a SWS homeostat, not a SWS+REMS homeostat. I am thinking of making REMS depend only on C, and not on S.  That seems reasonable to me.  If I have to justify this, perhaps I can find some papers that talk about a separate REMS homeostat.  
ASK JONATHAN AND JANNE ABOUT THIS!!
I ASKED JANNE AND SHE SEEMED TO THIS THAT MAKING REMS PROPENSITY DEPEND ONLY ON C AND NOT S WAS A GOOD IDEA

The problem with this approach is that even after sleep deprivation REMS will be just as likely because it depends only on C and not on S, so those SWS episodes probably won't be any longer because REMS is just as likely as normal.  

* Thursday, August 11, 2016
I am trying a new approach for REMS: make the probability proportional to 1-S.  This seems to sort of work, but I'm not getting the longer SWS episodes that I would like to see after sleep deprivation.  
I experimented with making ahatSR constant since in the Kemp paper they had a1R constant.  
Measure the aji values through smaller intervals (like 1h) to see if there are any that I can just treat as constants.  This may help reduce the complexity. 

I made this plot for 12 hours of the baseline.
ahatRW can be constant (and small)
ahatRS can be constant
ahatSR doesn't look so constant 

After first work day:
ahatRS is still constant
ahatSW is much larger, especially at the beginning (this is probably because of short W episodes after work shift)
ahatWR is lower after first work day
ahatSR is raised by about 50% just after work as compared to 


I can't seem to make the SWS episodes longer during Workdays as compared to baseline.  
Perhaps think about introducing a new "homeostat": the aWS and aRS that make SWS episodes longer (and REMS episodes longer) need to get much smaller 
during work and gradually increase over the course of the 16 hours following work.  This change seems to be more extreme than what S and C are going to give me.  


1:45:  I decided to try to make the time constant of the homeostat faster during work as compared to not during work.  This may be a bit of a stretch, but I don't see any other way to make those SWS episodes noticeably longer after work.  S-C is moving in the right direction, but not nearly enough.  I was thinking of ways to exagerate this movement, but the only thing I could think of would be a sort of reverse sigmoidal function which seems opposite of what usually happens in nature (THINK ABOUT STILL TRYING THIS!)  I'm modeling this using a cubic function. 
  Right now by making taui smaller during work I am seeing longer SWS episodes after workdays as compared to baseline, but not by much.  Keep working on optimizing this value.  

* Friday, August 12, 2016
I am working on the idea of using a cubic function for a_W_S.  This seems to be sort of working, but the length of SWS episodes dies down so quickly after the first couple of hours.  Should I try some kind of longer-lasting variable instead of a function of S and C?  Like a SWS episode length homeostat?  that has its own taui and taud values?  this could change with lights on and lights off.  Try this if my current idea doesn't pan out for 

SWS episode duration is long at first (first two hours) but then quickly shortens so that the overall average isn't really that high.  How can I change how quickly the SWS episodes get shorter?  

* Monday, August 15, 2016
If the plot for SWS episode duration vs. time looks good, the colored plot of state percentages does not look good.  

I tried using the taui and taud values that we calculated from our data using the simple homeostatic model and I was unable to get any substantial increase in the SWS episode duration after work.

Making ahat_RS=alpha(1-C) depend only on C and not S gives good agreement for the state percentages plot, but the episode durations plot is still way off.  Neither SWS episode duration nor REMS episode duration go up after work days.  

I included some code to not count a wake episode if it is only 1 epoch long.  This is consistent with what Jonathan does in his sleepreport.  He counts those as brief awakenings.  

It seems like S-C has dynamics that are too fast to match the dynamics in Figure 6 (colors).  Looking at the RW panel in Figure 6, the times between the work days have SWS percentages that are remarkably constant.  So far my model has a big spike of blue at the beginning and then a big dip and recovery.  Why is it constant in the data?  I am experimenting with using S-0.5*C instead of S-C.    

I made some changes to the parameters to make the colored percentages plot look nicer.  Now the Number of Wake episodes is way off, both for the baseline and the work days.  Way too many for the baseline day, and not enough for the work days.

3:42:  I'm back to the point where the baseline case looks good (runnning the code with the 'none' option).  I tweaked several parameters all at once and it was very tricky to balance them all out.  
Now, try to leave the ahat terms the same, and test the AW case and RW case.  If I have to adjust anything, try not to adjust anything that will affect the baseline.    

The colored plot doesn't look great for the RW case.  There is a lot of variation in the SWS percentage between shifts, but the data don't show this.  
The SWS duration plot shows a strong difference between AW and RW even though I am not using different tau values for the shift work like I was before. 
However, the number of wake episodes is very different during the work days between AW and RW even though the baseline is the same. 
IDEA: It seems that REMS should be more dependent on C than some of the other transition rates.  Right now I am using S-C + a constant for aSW and aSR, constant*(1-C) for aRS and alertness in aWS and aWR.  Perhaps I should make aRS depend more on C than these other rates.  Since change the shift has such a dramatic effect on number of wake episodes, that tells me that that parameter is very dependent on C.  Perhaps aRS should be very dependent on C, but the others not as much.  

* Tuesday, August 16, 2016
I made a plot of wake episode duration and RW have longer wake bouts between workdays than AW.  This could help explain why they have shorter SWS episodes, 
(since they have the same number of wake bouts as AW, but they are longer)  Since they are longer, something must get shorter and in this case it is SWS episode duration.  How can I see this in the model?  


* Saturday, August 20, 2016
I'm trying to get back to where I see a difference between AW and RW.  
I changed the c1,c2,c3,c4 (didn't bring the effect back)
I changed the ahat_S_W and ahat_S_R to being cubic again instead of the hybrid cubic/linear  (didn't bring the effect back)
I changed ahat_S_W back to being gamma*(S-C)-0.0010  (didn't bring back effect)
I changed taui and taud to be constant throughout the simulation (lines 197-198 in two_process_model_with_markov_chain.m) (this didn't bring the effect back)
The combo of changing the taui and taud to be constant and changing c1,c2,c3,c4 back to larger numbers brought the effect back where AW have longer SWS duration.  

