TTestResult.RestWork.TransitionType= char({ 'R2S' 'R2W' 'S2R' 'S2W' 'W2R' 'W2S'});

TTestResult.RestWork.RealMean(1,1)= mean(RSTrans1(find(max(char(shift)'=='R'))));
TTestResult.RestWork.RealSEM(1,1)= std(RSTrans1(find(max(char(shift)'=='R'))))/sqrt(size(RSTrans1(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.RealMean(2,1)= mean(RWTrans1(find(max(char(shift)'=='R'))));
TTestResult.RestWork.RealSEM(2,1)= std(RWTrans1(find(max(char(shift)'=='R'))))/sqrt(size(RWTrans1(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.RealMean(3,1)= mean(SRTrans1(find(max(char(shift)'=='R'))));
TTestResult.RestWork.RealSEM(3,1)= std(SRTrans1(find(max(char(shift)'=='R'))))/sqrt(size(SRTrans1(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.RealMean(4,1)= mean(SWTrans1(find(max(char(shift)'=='R'))));
TTestResult.RestWork.RealSEM(4,1)= std(SWTrans1(find(max(char(shift)'=='R'))))/sqrt(size(SWTrans1(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.RealMean(5,1)= mean(WRTrans1(find(max(char(shift)'=='R'))));
TTestResult.RestWork.RealSEM(5,1)= std(WRTrans1(find(max(char(shift)'=='R'))))/sqrt(size(WRTrans1(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.RealMean(6,1)= mean(WSTrans1(find(max(char(shift)'=='R'))));
TTestResult.RestWork.RealSEM(6,1)= std(WSTrans1(find(max(char(shift)'=='R'))))/sqrt(size(WSTrans1(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.SimuMean(1,1)= mean(R2Sbaseline(find(max(char(shift)'=='R'))));
TTestResult.RestWork.SimuSEM(1,1)= std(R2Sbaseline(find(max(char(shift)'=='R'))))/sqrt(size(R2Sbaseline(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.SimuMean(2,1)= mean(R2Wbaseline(find(max(char(shift)'=='R'))));
TTestResult.RestWork.SimuSEM(2,1)= std(R2Wbaseline(find(max(char(shift)'=='R'))))/sqrt(size(R2Wbaseline(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.SimuMean(3,1)= mean(S2Rbaseline(find(max(char(shift)'=='R'))));
TTestResult.RestWork.SimuSEM(3,1)= std(S2Rbaseline(find(max(char(shift)'=='R'))))/sqrt(size(S2Rbaseline(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.SimuMean(4,1)= mean(S2Wbaseline(find(max(char(shift)'=='R'))));
TTestResult.RestWork.SimuSEM(4,1)= std(S2Wbaseline(find(max(char(shift)'=='R'))))/sqrt(size(S2Wbaseline(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.SimuMean(5,1)= mean(W2Rbaseline(find(max(char(shift)'=='R'))));
TTestResult.RestWork.SimuSEM(5,1)= std(W2Rbaseline(find(max(char(shift)'=='R'))))/sqrt(size(W2Rbaseline(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.SimuMean(6,1)= mean(W2Sbaseline(find(max(char(shift)'=='R'))));
TTestResult.RestWork.SimuSEM(6,1)= std(W2Sbaseline(find(max(char(shift)'=='R'))))/sqrt(size(W2Sbaseline(find(max(char(shift)'=='R'))),2));
[junk, TTestResult.RestWork.TTestPValue(1,1)]= ttest2(RSTrans1(find(max(char(shift)'=='R')))',R2Sbaseline(find(max(char(shift)'=='R'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.RestWork.TTestPValue(2,1)]= ttest2(RWTrans1(find(max(char(shift)'=='R')))',R2Wbaseline(find(max(char(shift)'=='R'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.RestWork.TTestPValue(3,1)]= ttest2(SRTrans1(find(max(char(shift)'=='R')))',S2Rbaseline(find(max(char(shift)'=='R'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.RestWork.TTestPValue(4,1)]= ttest2(SWTrans1(find(max(char(shift)'=='R')))',S2Wbaseline(find(max(char(shift)'=='R'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.RestWork.TTestPValue(5,1)]= ttest2(WRTrans1(find(max(char(shift)'=='R')))',W2Rbaseline(find(max(char(shift)'=='R'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.RestWork.TTestPValue(6,1)]= ttest2(WSTrans1(find(max(char(shift)'=='R')))',W2Sbaseline(find(max(char(shift)'=='R'))),'Alpha',0.05/6,'Tail','both');

TTestResult.RestWork.RealMean(1,2)= mean(RSTrans2(find(max(char(shift)'=='R'))));
TTestResult.RestWork.RealSEM(1,2)= std(RSTrans2(find(max(char(shift)'=='R'))))/sqrt(size(RSTrans2(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.RealMean(2,2)= mean(RWTrans2(find(max(char(shift)'=='R'))));
TTestResult.RestWork.RealSEM(2,2)= std(RWTrans2(find(max(char(shift)'=='R'))))/sqrt(size(RWTrans2(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.RealMean(3,2)= mean(SRTrans2(find(max(char(shift)'=='R'))));
TTestResult.RestWork.RealSEM(3,2)= std(SRTrans2(find(max(char(shift)'=='R'))))/sqrt(size(SRTrans2(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.RealMean(4,2)= mean(SWTrans2(find(max(char(shift)'=='R'))));
TTestResult.RestWork.RealSEM(4,2)= std(SWTrans2(find(max(char(shift)'=='R'))))/sqrt(size(SWTrans2(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.RealMean(5,2)= mean(WRTrans2(find(max(char(shift)'=='R'))));
TTestResult.RestWork.RealSEM(5,2)= std(WRTrans2(find(max(char(shift)'=='R'))))/sqrt(size(WRTrans2(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.RealMean(6,2)= mean(WSTrans2(find(max(char(shift)'=='R'))));
TTestResult.RestWork.RealSEM(6,2)= std(WSTrans2(find(max(char(shift)'=='R'))))/sqrt(size(WSTrans2(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.SimuMean(1,2)= mean(R2S_W1(find(max(char(shift)'=='R'))));
TTestResult.RestWork.SimuSEM(1,2)= std(R2S_W1(find(max(char(shift)'=='R'))))/sqrt(size(R2S_W1(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.SimuMean(2,2)= mean(R2W_W1(find(max(char(shift)'=='R'))));
TTestResult.RestWork.SimuSEM(2,2)= std(R2W_W1(find(max(char(shift)'=='R'))))/sqrt(size(R2W_W1(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.SimuMean(3,2)= mean(S2R_W1(find(max(char(shift)'=='R'))));
TTestResult.RestWork.SimuSEM(3,2)= std(S2R_W1(find(max(char(shift)'=='R'))))/sqrt(size(S2R_W1(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.SimuMean(4,2)= mean(S2W_W1(find(max(char(shift)'=='R'))));
TTestResult.RestWork.SimuSEM(4,2)= std(S2W_W1(find(max(char(shift)'=='R'))))/sqrt(size(S2W_W1(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.SimuMean(5,2)= mean(W2R_W1(find(max(char(shift)'=='R'))));
TTestResult.RestWork.SimuSEM(5,2)= std(W2R_W1(find(max(char(shift)'=='R'))))/sqrt(size(W2R_W1(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.SimuMean(6,2)= mean(W2S_W1(find(max(char(shift)'=='R'))));
TTestResult.RestWork.SimuSEM(6,2)= std(W2S_W1(find(max(char(shift)'=='R'))))/sqrt(size(W2S_W1(find(max(char(shift)'=='R'))),2));
[junk, TTestResult.RestWork.TTestPValue(1,2)]= ttest2(RSTrans2(find(max(char(shift)'=='R')))',R2S_W1(find(max(char(shift)'=='R'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.RestWork.TTestPValue(2,2)]= ttest2(RWTrans2(find(max(char(shift)'=='R')))',R2W_W1(find(max(char(shift)'=='R'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.RestWork.TTestPValue(3,2)]= ttest2(SRTrans2(find(max(char(shift)'=='R')))',S2R_W1(find(max(char(shift)'=='R'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.RestWork.TTestPValue(4,2)]= ttest2(SWTrans2(find(max(char(shift)'=='R')))',S2W_W1(find(max(char(shift)'=='R'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.RestWork.TTestPValue(5,2)]= ttest2(WRTrans2(find(max(char(shift)'=='R')))',W2R_W1(find(max(char(shift)'=='R'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.RestWork.TTestPValue(6,2)]= ttest2(WSTrans2(find(max(char(shift)'=='R')))',W2S_W1(find(max(char(shift)'=='R'))),'Alpha',0.05/6,'Tail','both');

TTestResult.RestWork.RealMean(1,3)= mean(RSTrans3(find(max(char(shift)'=='R'))));
TTestResult.RestWork.RealSEM(1,3)= std(RSTrans3(find(max(char(shift)'=='R'))))/sqrt(size(RSTrans3(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.RealMean(2,3)= mean(RWTrans3(find(max(char(shift)'=='R'))));
TTestResult.RestWork.RealSEM(2,3)= std(RWTrans3(find(max(char(shift)'=='R'))))/sqrt(size(RWTrans3(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.RealMean(3,3)= mean(SRTrans3(find(max(char(shift)'=='R'))));
TTestResult.RestWork.RealSEM(3,3)= std(SRTrans3(find(max(char(shift)'=='R'))))/sqrt(size(SRTrans3(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.RealMean(4,3)= mean(SWTrans3(find(max(char(shift)'=='R'))));
TTestResult.RestWork.RealSEM(4,3)= std(SWTrans3(find(max(char(shift)'=='R'))))/sqrt(size(SWTrans3(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.RealMean(5,3)= mean(WRTrans3(find(max(char(shift)'=='R'))));
TTestResult.RestWork.RealSEM(5,3)= std(WRTrans3(find(max(char(shift)'=='R'))))/sqrt(size(WRTrans3(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.RealMean(6,3)= mean(WSTrans3(find(max(char(shift)'=='R'))));
TTestResult.RestWork.RealSEM(6,3)= std(WSTrans3(find(max(char(shift)'=='R'))))/sqrt(size(WSTrans3(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.SimuMean(1,3)= mean(R2S_W2(find(max(char(shift)'=='R'))));
TTestResult.RestWork.SimuSEM(1,3)= std(R2S_W2(find(max(char(shift)'=='R'))))/sqrt(size(R2S_W2(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.SimuMean(2,3)= mean(R2W_W2(find(max(char(shift)'=='R'))));
TTestResult.RestWork.SimuSEM(2,3)= std(R2W_W2(find(max(char(shift)'=='R'))))/sqrt(size(R2W_W2(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.SimuMean(3,3)= mean(S2R_W2(find(max(char(shift)'=='R'))));
TTestResult.RestWork.SimuSEM(3,3)= std(S2R_W2(find(max(char(shift)'=='R'))))/sqrt(size(S2R_W2(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.SimuMean(4,3)= mean(S2W_W2(find(max(char(shift)'=='R'))));
TTestResult.RestWork.SimuSEM(4,3)= std(S2W_W2(find(max(char(shift)'=='R'))))/sqrt(size(S2W_W2(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.SimuMean(5,3)= mean(W2R_W2(find(max(char(shift)'=='R'))));
TTestResult.RestWork.SimuSEM(5,3)= std(W2R_W2(find(max(char(shift)'=='R'))))/sqrt(size(W2R_W2(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.SimuMean(6,3)= mean(W2S_W2(find(max(char(shift)'=='R'))));
TTestResult.RestWork.SimuSEM(6,3)= std(W2S_W2(find(max(char(shift)'=='R'))))/sqrt(size(W2S_W2(find(max(char(shift)'=='R'))),2));
[junk, TTestResult.RestWork.TTestPValue(1,3)]= ttest2(RSTrans3(find(max(char(shift)'=='R')))',R2S_W2(find(max(char(shift)'=='R'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.RestWork.TTestPValue(2,3)]= ttest2(RWTrans3(find(max(char(shift)'=='R')))',R2W_W2(find(max(char(shift)'=='R'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.RestWork.TTestPValue(3,3)]= ttest2(SRTrans3(find(max(char(shift)'=='R')))',S2R_W2(find(max(char(shift)'=='R'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.RestWork.TTestPValue(4,3)]= ttest2(SWTrans3(find(max(char(shift)'=='R')))',S2W_W2(find(max(char(shift)'=='R'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.RestWork.TTestPValue(5,3)]= ttest2(WRTrans3(find(max(char(shift)'=='R')))',W2R_W2(find(max(char(shift)'=='R'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.RestWork.TTestPValue(6,3)]= ttest2(WSTrans3(find(max(char(shift)'=='R')))',W2S_W2(find(max(char(shift)'=='R'))),'Alpha',0.05/6,'Tail','both');

TTestResult.RestWork.RealMean(1,4)= mean(RSTrans4(find(max(char(shift)'=='R'))));
TTestResult.RestWork.RealSEM(1,4)= std(RSTrans4(find(max(char(shift)'=='R'))))/sqrt(size(RSTrans4(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.RealMean(2,4)= mean(RWTrans4(find(max(char(shift)'=='R'))));
TTestResult.RestWork.RealSEM(2,4)= std(RWTrans4(find(max(char(shift)'=='R'))))/sqrt(size(RWTrans4(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.RealMean(3,4)= mean(SRTrans4(find(max(char(shift)'=='R'))));
TTestResult.RestWork.RealSEM(3,4)= std(SRTrans4(find(max(char(shift)'=='R'))))/sqrt(size(SRTrans4(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.RealMean(4,4)= mean(SWTrans4(find(max(char(shift)'=='R'))));
TTestResult.RestWork.RealSEM(4,4)= std(SWTrans4(find(max(char(shift)'=='R'))))/sqrt(size(SWTrans4(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.RealMean(5,4)= mean(WRTrans4(find(max(char(shift)'=='R'))));
TTestResult.RestWork.RealSEM(5,4)= std(WRTrans4(find(max(char(shift)'=='R'))))/sqrt(size(WRTrans4(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.RealMean(6,4)= mean(WSTrans4(find(max(char(shift)'=='R'))));
TTestResult.RestWork.RealSEM(6,4)= std(WSTrans4(find(max(char(shift)'=='R'))))/sqrt(size(WSTrans4(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.SimuMean(1,4)= mean(R2S_W3(find(max(char(shift)'=='R'))));
TTestResult.RestWork.SimuSEM(1,4)= std(R2S_W3(find(max(char(shift)'=='R'))))/sqrt(size(R2S_W3(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.SimuMean(2,4)= mean(R2W_W3(find(max(char(shift)'=='R'))));
TTestResult.RestWork.SimuSEM(2,4)= std(R2W_W3(find(max(char(shift)'=='R'))))/sqrt(size(R2W_W3(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.SimuMean(3,4)= mean(S2R_W3(find(max(char(shift)'=='R'))));
TTestResult.RestWork.SimuSEM(3,4)= std(S2R_W3(find(max(char(shift)'=='R'))))/sqrt(size(S2R_W3(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.SimuMean(4,4)= mean(S2W_W3(find(max(char(shift)'=='R'))));
TTestResult.RestWork.SimuSEM(4,4)= std(S2W_W3(find(max(char(shift)'=='R'))))/sqrt(size(S2W_W3(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.SimuMean(5,4)= mean(W2R_W3(find(max(char(shift)'=='R'))));
TTestResult.RestWork.SimuSEM(5,4)= std(W2R_W3(find(max(char(shift)'=='R'))))/sqrt(size(W2R_W3(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.SimuMean(6,4)= mean(W2S_W3(find(max(char(shift)'=='R'))));
TTestResult.RestWork.SimuSEM(6,4)= std(W2S_W3(find(max(char(shift)'=='R'))))/sqrt(size(W2S_W3(find(max(char(shift)'=='R'))),2));
[junk, TTestResult.RestWork.TTestPValue(1,4)]= ttest2(RSTrans4(find(max(char(shift)'=='R')))',R2S_W3(find(max(char(shift)'=='R'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.RestWork.TTestPValue(2,4)]= ttest2(RWTrans4(find(max(char(shift)'=='R')))',R2W_W3(find(max(char(shift)'=='R'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.RestWork.TTestPValue(3,4)]= ttest2(SRTrans4(find(max(char(shift)'=='R')))',S2R_W3(find(max(char(shift)'=='R'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.RestWork.TTestPValue(4,4)]= ttest2(SWTrans4(find(max(char(shift)'=='R')))',S2W_W3(find(max(char(shift)'=='R'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.RestWork.TTestPValue(5,4)]= ttest2(WRTrans4(find(max(char(shift)'=='R')))',W2R_W3(find(max(char(shift)'=='R'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.RestWork.TTestPValue(6,4)]= ttest2(WSTrans4(find(max(char(shift)'=='R')))',W2S_W3(find(max(char(shift)'=='R'))),'Alpha',0.05/6,'Tail','both');

TTestResult.RestWork.RealMean(1,5)= mean(RSTrans5(find(max(char(shift)'=='R'))));
TTestResult.RestWork.RealSEM(1,5)= std(RSTrans5(find(max(char(shift)'=='R'))))/sqrt(size(RSTrans5(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.RealMean(2,5)= mean(RWTrans5(find(max(char(shift)'=='R'))));
TTestResult.RestWork.RealSEM(2,5)= std(RWTrans5(find(max(char(shift)'=='R'))))/sqrt(size(RWTrans5(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.RealMean(3,5)= mean(SRTrans5(find(max(char(shift)'=='R'))));
TTestResult.RestWork.RealSEM(3,5)= std(SRTrans5(find(max(char(shift)'=='R'))))/sqrt(size(SRTrans5(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.RealMean(4,5)= mean(SWTrans5(find(max(char(shift)'=='R'))));
TTestResult.RestWork.RealSEM(4,5)= std(SWTrans5(find(max(char(shift)'=='R'))))/sqrt(size(SWTrans5(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.RealMean(5,5)= mean(WRTrans5(find(max(char(shift)'=='R'))));
TTestResult.RestWork.RealSEM(5,5)= std(WRTrans5(find(max(char(shift)'=='R'))))/sqrt(size(WRTrans5(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.RealMean(6,5)= mean(WSTrans5(find(max(char(shift)'=='R'))));
TTestResult.RestWork.RealSEM(6,5)= std(WSTrans5(find(max(char(shift)'=='R'))))/sqrt(size(WSTrans5(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.SimuMean(1,5)= mean(R2S_W4(find(max(char(shift)'=='R'))));
TTestResult.RestWork.SimuSEM(1,5)= std(R2S_W4(find(max(char(shift)'=='R'))))/sqrt(size(R2S_W4(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.SimuMean(2,5)= mean(R2W_W4(find(max(char(shift)'=='R'))));
TTestResult.RestWork.SimuSEM(2,5)= std(R2W_W4(find(max(char(shift)'=='R'))))/sqrt(size(R2W_W4(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.SimuMean(3,5)= mean(S2R_W4(find(max(char(shift)'=='R'))));
TTestResult.RestWork.SimuSEM(3,5)= std(S2R_W4(find(max(char(shift)'=='R'))))/sqrt(size(S2R_W4(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.SimuMean(4,5)= mean(S2W_W4(find(max(char(shift)'=='R'))));
TTestResult.RestWork.SimuSEM(4,5)= std(S2W_W4(find(max(char(shift)'=='R'))))/sqrt(size(S2W_W4(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.SimuMean(5,5)= mean(W2R_W4(find(max(char(shift)'=='R'))));
TTestResult.RestWork.SimuSEM(5,5)= std(W2R_W4(find(max(char(shift)'=='R'))))/sqrt(size(W2R_W4(find(max(char(shift)'=='R'))),2));
TTestResult.RestWork.SimuMean(6,5)= mean(W2S_W4(find(max(char(shift)'=='R'))));
TTestResult.RestWork.SimuSEM(6,5)= std(W2S_W4(find(max(char(shift)'=='R'))))/sqrt(size(W2S_W4(find(max(char(shift)'=='R'))),2));
[junk, TTestResult.RestWork.TTestPValue(1,5)]= ttest2(RSTrans5(find(max(char(shift)'=='R')))',R2S_W4(find(max(char(shift)'=='R'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.RestWork.TTestPValue(2,5)]= ttest2(RWTrans5(find(max(char(shift)'=='R')))',R2W_W4(find(max(char(shift)'=='R'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.RestWork.TTestPValue(3,5)]= ttest2(SRTrans5(find(max(char(shift)'=='R')))',S2R_W4(find(max(char(shift)'=='R'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.RestWork.TTestPValue(4,5)]= ttest2(SWTrans5(find(max(char(shift)'=='R')))',S2W_W4(find(max(char(shift)'=='R'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.RestWork.TTestPValue(5,5)]= ttest2(WRTrans5(find(max(char(shift)'=='R')))',W2R_W4(find(max(char(shift)'=='R'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.RestWork.TTestPValue(6,5)]= ttest2(WSTrans5(find(max(char(shift)'=='R')))',W2S_W4(find(max(char(shift)'=='R'))),'Alpha',0.05/6,'Tail','both');

writetable(struct2table(TTestResult.RestWork),'Z:\MATLAB\Rempe\Shift_work_project\RestWork_T_TestTable.csv');

TTestResult.ActiveWork.Transition= char({ 'R2S' 'R2W' 'S2R' 'S2W' 'W2R' 'W2S'});
TTestResult.ActiveWork.RealMean(1,1)= mean(RSTrans1(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.RealSEM(1,1)= std(RSTrans1(find(max(char(shift)'=='A'))))/sqrt(size(RSTrans1(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.RealMean(2,1)= mean(RWTrans1(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.RealSEM(2,1)= std(RWTrans1(find(max(char(shift)'=='A'))))/sqrt(size(RWTrans1(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.RealMean(3,1)= mean(SRTrans1(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.RealSEM(3,1)= std(SRTrans1(find(max(char(shift)'=='A'))))/sqrt(size(SRTrans1(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.RealMean(4,1)= mean(SWTrans1(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.RealSEM(4,1)= std(SWTrans1(find(max(char(shift)'=='A'))))/sqrt(size(SWTrans1(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.RealMean(5,1)= mean(WRTrans1(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.RealSEM(5,1)= std(WRTrans1(find(max(char(shift)'=='A'))))/sqrt(size(WRTrans1(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.RealMean(6,1)= mean(WSTrans1(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.RealSEM(6,1)= std(WSTrans1(find(max(char(shift)'=='A'))))/sqrt(size(WSTrans1(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.SimuMean(1,1)= mean(R2Sbaseline(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.SimuSEM(1,1)= std(R2Sbaseline(find(max(char(shift)'=='A'))))/sqrt(size(R2Sbaseline(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.SimuMean(2,1)= mean(R2Wbaseline(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.SimuSEM(2,1)= std(R2Wbaseline(find(max(char(shift)'=='A'))))/sqrt(size(R2Wbaseline(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.SimuMean(3,1)= mean(S2Rbaseline(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.SimuSEM(3,1)= std(S2Rbaseline(find(max(char(shift)'=='A'))))/sqrt(size(S2Rbaseline(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.SimuMean(4,1)= mean(S2Wbaseline(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.SimuSEM(4,1)= std(S2Wbaseline(find(max(char(shift)'=='A'))))/sqrt(size(S2Wbaseline(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.SimuMean(5,1)= mean(W2Rbaseline(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.SimuSEM(5,1)= std(W2Rbaseline(find(max(char(shift)'=='A'))))/sqrt(size(W2Rbaseline(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.SimuMean(6,1)= mean(W2Sbaseline(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.SimuSEM(6,1)= std(W2Sbaseline(find(max(char(shift)'=='A'))))/sqrt(size(W2Sbaseline(find(max(char(shift)'=='A'))),2));
[junk, TTestResult.ActiveWork.TTestPValue(1,1)]= ttest2(RSTrans1(find(max(char(shift)'=='A')))',R2Sbaseline(find(max(char(shift)'=='A'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.ActiveWork.TTestPValue(2,1)]= ttest2(RWTrans1(find(max(char(shift)'=='A')))',R2Wbaseline(find(max(char(shift)'=='A'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.ActiveWork.TTestPValue(3,1)]= ttest2(SRTrans1(find(max(char(shift)'=='A')))',S2Rbaseline(find(max(char(shift)'=='A'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.ActiveWork.TTestPValue(4,1)]= ttest2(SWTrans1(find(max(char(shift)'=='A')))',S2Wbaseline(find(max(char(shift)'=='A'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.ActiveWork.TTestPValue(5,1)]= ttest2(WRTrans1(find(max(char(shift)'=='A')))',W2Rbaseline(find(max(char(shift)'=='A'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.ActiveWork.TTestPValue(6,1)]= ttest2(WSTrans1(find(max(char(shift)'=='A')))',W2Sbaseline(find(max(char(shift)'=='A'))),'Alpha',0.05/6,'Tail','both');

TTestResult.ActiveWork.RealMean(1,2)= mean(RSTrans2(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.RealSEM(1,2)= std(RSTrans2(find(max(char(shift)'=='A'))))/sqrt(size(RSTrans2(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.RealMean(2,2)= mean(RWTrans2(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.RealSEM(2,2)= std(RWTrans2(find(max(char(shift)'=='A'))))/sqrt(size(RWTrans2(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.RealMean(3,2)= mean(SRTrans2(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.RealSEM(3,2)= std(SRTrans2(find(max(char(shift)'=='A'))))/sqrt(size(SRTrans2(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.RealMean(4,2)= mean(SWTrans2(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.RealSEM(4,2)= std(SWTrans2(find(max(char(shift)'=='A'))))/sqrt(size(SWTrans2(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.RealMean(5,2)= mean(WRTrans2(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.RealSEM(5,2)= std(WRTrans2(find(max(char(shift)'=='A'))))/sqrt(size(WRTrans2(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.RealMean(6,2)= mean(WSTrans2(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.RealSEM(6,2)= std(WSTrans2(find(max(char(shift)'=='A'))))/sqrt(size(WSTrans2(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.SimuMean(1,2)= mean(R2S_W1(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.SimuSEM(1,2)= std(R2S_W1(find(max(char(shift)'=='A'))))/sqrt(size(R2S_W1(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.SimuMean(2,2)= mean(R2W_W1(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.SimuSEM(2,2)= std(R2W_W1(find(max(char(shift)'=='A'))))/sqrt(size(R2W_W1(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.SimuMean(3,2)= mean(S2R_W1(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.SimuSEM(3,2)= std(S2R_W1(find(max(char(shift)'=='A'))))/sqrt(size(S2R_W1(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.SimuMean(4,2)= mean(S2W_W1(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.SimuSEM(4,2)= std(S2W_W1(find(max(char(shift)'=='A'))))/sqrt(size(S2W_W1(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.SimuMean(5,2)= mean(W2R_W1(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.SimuSEM(5,2)= std(W2R_W1(find(max(char(shift)'=='A'))))/sqrt(size(W2R_W1(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.SimuMean(6,2)= mean(W2S_W1(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.SimuSEM(6,2)= std(W2S_W1(find(max(char(shift)'=='A'))))/sqrt(size(W2S_W1(find(max(char(shift)'=='A'))),2));
[junk, TTestResult.ActiveWork.TTestPValue(1,2)]= ttest2(RSTrans2(find(max(char(shift)'=='A')))',R2S_W1(find(max(char(shift)'=='A'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.ActiveWork.TTestPValue(2,2)]= ttest2(RWTrans2(find(max(char(shift)'=='A')))',R2W_W1(find(max(char(shift)'=='A'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.ActiveWork.TTestPValue(3,2)]= ttest2(SRTrans2(find(max(char(shift)'=='A')))',S2R_W1(find(max(char(shift)'=='A'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.ActiveWork.TTestPValue(4,2)]= ttest2(SWTrans2(find(max(char(shift)'=='A')))',S2W_W1(find(max(char(shift)'=='A'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.ActiveWork.TTestPValue(5,2)]= ttest2(WRTrans2(find(max(char(shift)'=='A')))',W2R_W1(find(max(char(shift)'=='A'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.ActiveWork.TTestPValue(6,2)]= ttest2(WSTrans2(find(max(char(shift)'=='A')))',W2S_W1(find(max(char(shift)'=='A'))),'Alpha',0.05/6,'Tail','both');

TTestResult.ActiveWork.RealMean(1,3)= mean(RSTrans3(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.RealSEM(1,3)= std(RSTrans3(find(max(char(shift)'=='A'))))/sqrt(size(RSTrans3(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.RealMean(2,3)= mean(RWTrans3(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.RealSEM(2,3)= std(RWTrans3(find(max(char(shift)'=='A'))))/sqrt(size(RWTrans3(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.RealMean(3,3)= mean(SRTrans3(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.RealSEM(3,3)= std(SRTrans3(find(max(char(shift)'=='A'))))/sqrt(size(SRTrans3(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.RealMean(4,3)= mean(SWTrans3(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.RealSEM(4,3)= std(SWTrans3(find(max(char(shift)'=='A'))))/sqrt(size(SWTrans3(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.RealMean(5,3)= mean(WRTrans3(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.RealSEM(5,3)= std(WRTrans3(find(max(char(shift)'=='A'))))/sqrt(size(WRTrans3(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.RealMean(6,3)= mean(WSTrans3(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.RealSEM(6,3)= std(WSTrans3(find(max(char(shift)'=='A'))))/sqrt(size(WSTrans3(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.SimuMean(1,3)= mean(R2S_W2(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.SimuSEM(1,3)= std(R2S_W2(find(max(char(shift)'=='A'))))/sqrt(size(R2S_W2(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.SimuMean(2,3)= mean(R2W_W2(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.SimuSEM(2,3)= std(R2W_W2(find(max(char(shift)'=='A'))))/sqrt(size(R2W_W2(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.SimuMean(3,3)= mean(S2R_W2(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.SimuSEM(3,3)= std(S2R_W2(find(max(char(shift)'=='A'))))/sqrt(size(S2R_W2(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.SimuMean(4,3)= mean(S2W_W2(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.SimuSEM(4,3)= std(S2W_W2(find(max(char(shift)'=='A'))))/sqrt(size(S2W_W2(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.SimuMean(5,3)= mean(W2R_W2(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.SimuSEM(5,3)= std(W2R_W2(find(max(char(shift)'=='A'))))/sqrt(size(W2R_W2(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.SimuMean(6,3)= mean(W2S_W2(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.SimuSEM(6,3)= std(W2S_W2(find(max(char(shift)'=='A'))))/sqrt(size(W2S_W2(find(max(char(shift)'=='A'))),2));
[junk, TTestResult.ActiveWork.TTestPValue(1,3)]= ttest2(RSTrans3(find(max(char(shift)'=='A')))',R2S_W2(find(max(char(shift)'=='A'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.ActiveWork.TTestPValue(2,3)]= ttest2(RWTrans3(find(max(char(shift)'=='A')))',R2W_W2(find(max(char(shift)'=='A'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.ActiveWork.TTestPValue(3,3)]= ttest2(SRTrans3(find(max(char(shift)'=='A')))',S2R_W2(find(max(char(shift)'=='A'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.ActiveWork.TTestPValue(4,3)]= ttest2(SWTrans3(find(max(char(shift)'=='A')))',S2W_W2(find(max(char(shift)'=='A'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.ActiveWork.TTestPValue(5,3)]= ttest2(WRTrans3(find(max(char(shift)'=='A')))',W2R_W2(find(max(char(shift)'=='A'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.ActiveWork.TTestPValue(6,3)]= ttest2(WSTrans3(find(max(char(shift)'=='A')))',W2S_W2(find(max(char(shift)'=='A'))),'Alpha',0.05/6,'Tail','both');

TTestResult.ActiveWork.RealMean(1,4)= mean(RSTrans4(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.RealSEM(1,4)= std(RSTrans4(find(max(char(shift)'=='A'))))/sqrt(size(RSTrans4(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.RealMean(2,4)= mean(RWTrans4(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.RealSEM(2,4)= std(RWTrans4(find(max(char(shift)'=='A'))))/sqrt(size(RWTrans4(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.RealMean(3,4)= mean(SRTrans4(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.RealSEM(3,4)= std(SRTrans4(find(max(char(shift)'=='A'))))/sqrt(size(SRTrans4(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.RealMean(4,4)= mean(SWTrans4(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.RealSEM(4,4)= std(SWTrans4(find(max(char(shift)'=='A'))))/sqrt(size(SWTrans4(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.RealMean(5,4)= mean(WRTrans4(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.RealSEM(5,4)= std(WRTrans4(find(max(char(shift)'=='A'))))/sqrt(size(WRTrans4(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.RealMean(6,4)= mean(WSTrans4(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.RealSEM(6,4)= std(WSTrans4(find(max(char(shift)'=='A'))))/sqrt(size(WSTrans4(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.SimuMean(1,4)= mean(R2S_W3(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.SimuSEM(1,4)= std(R2S_W3(find(max(char(shift)'=='A'))))/sqrt(size(R2S_W3(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.SimuMean(2,4)= mean(R2W_W3(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.SimuSEM(2,4)= std(R2W_W3(find(max(char(shift)'=='A'))))/sqrt(size(R2W_W3(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.SimuMean(3,4)= mean(S2R_W3(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.SimuSEM(3,4)= std(S2R_W3(find(max(char(shift)'=='A'))))/sqrt(size(S2R_W3(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.SimuMean(4,4)= mean(S2W_W3(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.SimuSEM(4,4)= std(S2W_W3(find(max(char(shift)'=='A'))))/sqrt(size(S2W_W3(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.SimuMean(5,4)= mean(W2R_W3(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.SimuSEM(5,4)= std(W2R_W3(find(max(char(shift)'=='A'))))/sqrt(size(W2R_W3(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.SimuMean(6,4)= mean(W2S_W3(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.SimuSEM(6,4)= std(W2S_W3(find(max(char(shift)'=='A'))))/sqrt(size(W2S_W3(find(max(char(shift)'=='A'))),2));
[junk, TTestResult.ActiveWork.TTestPValue(1,4)]= ttest2(RSTrans4(find(max(char(shift)'=='A')))',R2S_W3(find(max(char(shift)'=='A'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.ActiveWork.TTestPValue(2,4)]= ttest2(RWTrans4(find(max(char(shift)'=='A')))',R2W_W3(find(max(char(shift)'=='A'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.ActiveWork.TTestPValue(3,4)]= ttest2(SRTrans4(find(max(char(shift)'=='A')))',S2R_W3(find(max(char(shift)'=='A'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.ActiveWork.TTestPValue(4,4)]= ttest2(SWTrans4(find(max(char(shift)'=='A')))',S2W_W3(find(max(char(shift)'=='A'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.ActiveWork.TTestPValue(5,4)]= ttest2(WRTrans4(find(max(char(shift)'=='A')))',W2R_W3(find(max(char(shift)'=='A'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.ActiveWork.TTestPValue(6,4)]= ttest2(WSTrans4(find(max(char(shift)'=='A')))',W2S_W3(find(max(char(shift)'=='A'))),'Alpha',0.05/6,'Tail','both');

TTestResult.ActiveWork.RealMean(1,5)= mean(RSTrans5(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.RealSEM(1,5)= std(RSTrans5(find(max(char(shift)'=='A'))))/sqrt(size(RSTrans5(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.RealMean(2,5)= mean(RWTrans5(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.RealSEM(2,5)= std(RWTrans5(find(max(char(shift)'=='A'))))/sqrt(size(RWTrans5(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.RealMean(3,5)= mean(SRTrans5(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.RealSEM(3,5)= std(SRTrans5(find(max(char(shift)'=='A'))))/sqrt(size(SRTrans5(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.RealMean(4,5)= mean(SWTrans5(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.RealSEM(4,5)= std(SWTrans5(find(max(char(shift)'=='A'))))/sqrt(size(SWTrans5(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.RealMean(5,5)= mean(WRTrans5(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.RealSEM(5,5)= std(WRTrans5(find(max(char(shift)'=='A'))))/sqrt(size(WRTrans5(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.RealMean(6,5)= mean(WSTrans5(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.RealSEM(6,5)= std(WSTrans5(find(max(char(shift)'=='A'))))/sqrt(size(WSTrans5(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.SimuMean(1,5)= mean(R2S_W4(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.SimuSEM(1,5)= std(R2S_W4(find(max(char(shift)'=='A'))))/sqrt(size(R2S_W4(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.SimuMean(2,5)= mean(R2W_W4(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.SimuSEM(2,5)= std(R2W_W4(find(max(char(shift)'=='A'))))/sqrt(size(R2W_W4(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.SimuMean(3,5)= mean(S2R_W4(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.SimuSEM(3,5)= std(S2R_W4(find(max(char(shift)'=='A'))))/sqrt(size(S2R_W4(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.SimuMean(4,5)= mean(S2W_W4(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.SimuSEM(4,5)= std(S2W_W4(find(max(char(shift)'=='A'))))/sqrt(size(S2W_W4(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.SimuMean(5,5)= mean(W2R_W4(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.SimuSEM(5,5)= std(W2R_W4(find(max(char(shift)'=='A'))))/sqrt(size(W2R_W4(find(max(char(shift)'=='A'))),2));
TTestResult.ActiveWork.SimuMean(6,5)= mean(W2S_W4(find(max(char(shift)'=='A'))));
TTestResult.ActiveWork.SimuSEM(6,5)= std(W2S_W4(find(max(char(shift)'=='A'))))/sqrt(size(W2S_W4(find(max(char(shift)'=='A'))),2));
[junk, TTestResult.ActiveWork.TTestPValue(1,5)]= ttest2(RSTrans5(find(max(char(shift)'=='A')))',R2S_W4(find(max(char(shift)'=='A'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.ActiveWork.TTestPValue(2,5)]= ttest2(RWTrans5(find(max(char(shift)'=='A')))',R2W_W4(find(max(char(shift)'=='A'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.ActiveWork.TTestPValue(3,5)]= ttest2(SRTrans5(find(max(char(shift)'=='A')))',S2R_W4(find(max(char(shift)'=='A'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.ActiveWork.TTestPValue(4,5)]= ttest2(SWTrans5(find(max(char(shift)'=='A')))',S2W_W4(find(max(char(shift)'=='A'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.ActiveWork.TTestPValue(5,5)]= ttest2(WRTrans5(find(max(char(shift)'=='A')))',W2R_W4(find(max(char(shift)'=='A'))),'Alpha',0.05/6,'Tail','both');
[junk, TTestResult.ActiveWork.TTestPValue(6,5)]= ttest2(WSTrans5(find(max(char(shift)'=='A')))',W2S_W4(find(max(char(shift)'=='A'))),'Alpha',0.05/6,'Tail','both');

writetable(struct2table(TTestResult.ActiveWork),'Z:\MATLAB\Rempe\Shift_work_project\ActiveWork_T_TestTable.csv');